# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-28 12:44
from __future__ import unicode_literals

import ccposts.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='\u6807\u9898')),
                ('body', models.TextField(blank=True, verbose_name='\u6b63\u6587')),
                ('abstract', models.CharField(blank=True, help_text='\u5982\u65e0\uff0c\u622a\u53d6\u6587\u7ae0\u524d200\u5b57\uff01', max_length=200, verbose_name='\u6458\u8981')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name='\u4e0a\u6b21\u4fee\u6539\u65f6\u95f4')),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Published')], max_length=1, verbose_name='\u6587\u7ae0\u72b6\u6001')),
                ('slug', models.SlugField(unique=True)),
                ('commentcount', models.PositiveIntegerField(blank=True, default=0, verbose_name='\u8bc4\u8bba\u6570')),
                ('views', models.PositiveIntegerField(blank=True, default=0, verbose_name='\u6d4f\u89c8\u91cf')),
                ('likes', models.PositiveIntegerField(blank=True, default=0, verbose_name='\u70b9\u8d5e\u6570')),
                ('topped', models.NullBooleanField(default=True, verbose_name='\u7f6e\u9876')),
                ('html_file', models.FileField(blank=True, upload_to=ccposts.models.get_html_name, verbose_name='\u4e0a\u4f20html\u6587\u4ef6')),
                ('md_file', models.FileField(blank=True, upload_to=ccposts.models.get_upload_md_name, verbose_name='\u4e0a\u4f20md\u6587\u4ef6')),
            ],
            options={
                'ordering': ['-last_modified_time'],
            },
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=ccposts.models.get_upload_img_name)),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='\u4e0a\u4f20\u65f6\u95f4')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ccposts.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(max_length=30, verbose_name='\u76ee\u5f55\u540d\u79f0')),
                ('articlecount', models.PositiveIntegerField(default=0, verbose_name='\u6587\u7ae0\u7bc7\u6570')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(max_length=30, verbose_name='\u6807\u7b7e\u540d')),
                ('articlecount', models.PositiveIntegerField(default=0, verbose_name='\u6807\u7b7e\u4e0b\u6587\u7ae0\u6570')),
            ],
            options={
                'ordering': ['tagname'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccposts.Category', verbose_name='\u76ee\u5f55'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='ccposts.Tag', verbose_name='\u6807\u7b7e'),
        ),
    ]
